const ADD_PATIENTS = 'ADD_PATIENTS';
const CHANGE_SEARCH_PATIENTS = 'CHANGE_SEARCH_PATIENTS';
const CHANGE_SEARCH_COUNTRY = 'CHANGE_SEARCH_COUNTRY';
const CHANGE_GENDER = 'CHANGE_GENDER';
const SET_LIST_LENGTH = 'SET_LIST_LENGTH';

export {
    ADD_PATIENTS,
    CHANGE_SEARCH_PATIENTS,
    CHANGE_SEARCH_COUNTRY,
    CHANGE_GENDER,
    SET_LIST_LENGTH
};