const ADD_PATIENTS = 'ADD_PATIENTS';
const CHANGE_SEARCH_PATIENTS = 'CHANGE_SEARCH_PATIENTS';
const CHANGE_SEARCH_COUNTRY = 'CHANGE_SEARCH_COUNTRY';
const CHANGE_ORDER_BY = 'CHANGE_ORDER_BY';
const CHANGE_ORDER = 'CHANGE_ORDER';
const CHANGE_GENDER = 'CHANGE_GENDER';

export {
    ADD_PATIENTS,
    CHANGE_SEARCH_PATIENTS,
    CHANGE_SEARCH_COUNTRY,
    CHANGE_ORDER_BY,
    CHANGE_ORDER,
    CHANGE_GENDER
};